run:
  exclude-dirs-use-default: false
linters-settings:
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - "^print$"
      - "^println$"
      - "^panic$"
    analyze-types: true
  godox:
    # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
    # temporary hacks, and use godox to prevent committing them.
    keywords: [FIXME]
  varnamelen:
    max-distance: 20
    ignore-decls:
      - T any
      - i int
      - wg sync.WaitGroup
      - eg *errgroup.Group
  importas:
    # Do not allow unaliased imports of aliased packages.
    # Default: false
    no-unaliased: false
    # Do not allow non-required aliases.
    # Default: false
    no-extra-aliases: false
    # List of aliases
    # Default: []
    alias:
      - pkg: bitbucket.org/thetalake/common/logging/log
        alias: tl_log
  depguard:
    rules:
      main:
        list-mode: lax
        deny:
          - pkg: "bitbucket.org/thetalake/common/typedetect"
            desc: not allowed
linters:
  enable-all: true
  disable:
    - tagalign # tagalign makes you align struct tags, which IDEs don't do
    - unparam # don't warn on unused parameters and return values
    - cyclop # covered by gocyclo
    - deadcode # abandoned
    - exhaustivestruct # replaced by exhaustruct
    - funlen # rely on code review to limit function length
    - gocognit # dubious "cognitive overhead" quantification
    - gofumpt # prefer standard gofmt
    - goimports # rely on gci instead
    - golint # deprecated by Go team
    - gomnd # some unnamed constants are okay
    - ifshort # deprecated by author
    - interfacer # deprecated by author
    - ireturn # "accept interfaces, return structs" isn't ironclad
    - lll # don't want hard limits for line length
    - maintidx # covered by gocyclo
    - maligned # readability trumps efficient struct packing
    - nlreturn # generous whitespace violates house style
    - nosnakecase # deprecated in https://github.com/golangci/golangci-lint/pull/3065
    - paralleltest # in this project, it's not worth making all tests parallel
    - scopelint # deprecated by author
    - structcheck # abandoned
    - testpackage # internal tests are fine
    - tparallel # in this project, it's not worth making all tests parallel
    - varcheck # abandoned
    - wrapcheck # don't _always_ need to wrap errors
    - wsl # generous whitespace violates house style
    - gosec # complaining about converting int -> uint
    - mnd # we don't mind magic numbers
    - gochecknoglobals
    - gochecknoinits
    - exhaustruct
issues:
  exclude:
    # Don't ban use of fmt.Errorf to create new errors, but the remaining
    # checks from err113 are useful.
    - "do not define dynamic errors.*"
